# Generated by Django 2.0.1 on 2018-01-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='use',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
