# Generated by Django 2.0.1 on 2018-01-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0002_projects_use'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
