# Generated by Django 2.0.1 on 2018-01-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('try', '0004_auto_20180131_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Model',
        ),
    ]
